# Generated by Django 4.2.7 on 2023-11-23 21:25

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('business_name', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zip', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=255)),
                ('history', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Business/logos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='Business/cover_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='HarmonixUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_type', models.CharField(choices=[('Business owner', 'Business owner'), ('Job seeker', 'Job seeker')], default='Job seeker', max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='User/images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('resume', models.FileField(blank=True, null=True, upload_to='Professional/resumes/')),
                ('portfolio', models.CharField(max_length=255)),
                ('preferences', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Professional/avatars/')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('requirements', models.CharField(max_length=255)),
                ('benefits', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('contacts', models.CharField(max_length=255)),
                ('How_to_apply', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Harmonix.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='Professional/resumes/')),
                ('cover_letter', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Harmonix.professionalprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Harmonix.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Bug report', 'Bug report'), ('Feature request', 'Feature request'), ('general feedback', 'general feedback'), ('complaint', 'complaint'), ('other', 'other')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
