# Generated by Django 4.2.7 on 2023-11-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Harmonix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='businessprofile',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='businessprofile',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='businessprofile',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='businessprofile',
            old_name='Website',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='businessprofile',
            old_name='Name',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='Zip',
        ),
    ]
