# Generated by Django 4.2.7 on 2023-11-23 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Harmonix', '0002_rename_address_businessprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='businessprofile',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='type',
            new_name='feedback_type',
        ),
        migrations.RenameField(
            model_name='professionalprofile',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
